apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: postgres
  name: postgres
  namespace: monitoring
spec:
  endpoints:
  - interval: 10s
    targetPort: 9187
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: prometheus-postgres-exporter
