# helm upgrade prometheus stable/prometheus-operator --install --namespace monitoring -f prometheus.yml

# https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

fullnameOverride: prometheus

#### we have our own grafana instance
grafana:
  enabled: false

### following resources either controlled by GKE or absent
kubeDns:
  enabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
defaultRules:
  rules:
    etcd: false
    kubeApiserver: false
    kubeScheduler: false

### settings for the alert manager
alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 24h
      receiver: bowser-pager
      # routes:
      # - match:
      #     alertname: DeadMansSwitch
      #   receiver: "null"
    receivers:
    - name: "null"
    - name: bowser-pager
      opsgenie_configs:
      - api_key: c55c936e-e13e-4a74-b8ae-79344ad825bd


prometheus:
  prometheusSpec:
    ruleSelector:
      matchExpressions:
      - key: app
        operator: Exists
    serviceMonitorSelector:
      matchExpressions:
      - key: app
        operator: Exists
