fullnameOverride: amqp
replicaCount: 3
rabbitmqUsername: guest
# rabbitmqPassword: xxx
# rabbitmqErlangCookie: xxx
rabbitmqErlangCookie: "6mePTNBF22UPQVDp84Ny8EKj7kwom9X"

terminationGracePeriodSeconds: 1

rabbitmqMemoryHighWatermark: 1024MB

updateStrategy: RollingUpdate

definitions:
  policies: |-
    {
      "name": "ha-all",
      "pattern": ".*",
      "vhost": "/",
      "definition": {
        "ha-mode": "all",
        "ha-sync-mode": "automatic",
        "ha-sync-batch-size": 1
      }
    }

# persistentVolume:
#   enabled: true

# NOTE: we enable exporter but do implement custom servicemonitors / prometheus rules
prometheus:
  exporter:
    enabled: true
  operator:
    enabled: false
    alerts:
      enabled: false

resources:
  requests:
    cpu: 300m
    memory: 1024Mi
