# resources:
# - apiVersion: certmanager.k8s.io/v1alpha1
#   kind: ClusterIssuer
#   metadata:
#     name: letsencrypt
#     namespace: infrastructure
#   spec:
#     acme:
#       server: https://acme-v02.api.letsencrypt.org/directory
#       email: v@makeomatic.ca
#       # http01: {}
#       privateKeySecretRef:
#         name: letsencrypt
#       dns01:
#         providers:
#         - name: cloudflare
#           cloudflare:
#             email: k.popov@cappasity.com
#             apiKeySecretRef:
#               name: cloudflare-token
#               key: token

# - apiVersion: certmanager.k8s.io/v1alpha1
#   kind: Certificate
#   metadata:
#     name: istio.cappasity3d.com
#     namespace: istio-system
#   spec:
#     secretName: istio-wild-crt
#     commonName: "*.istio.cappasity3d.com"
#     dnsNames:
#       - istio.cappasity3d.com
#     acme:
#       config:
#       - dns01:
#           provider: cloudflare
#         domains:
#         - "*.istio.cappasity3d.com"
#         - "istio.cappasity3d.com"
#     issuerRef:
#       name: letsencrypt
#       kind: ClusterIssuer
