loki:
  replicas: 1
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      memory: 128Mi

  persistence:
    enabled: true
    size: 100Gi

promtail:
  resources:
    requests:
      cpu: 500m
      memory: 128Mi
    limits:
      memory: 128Mi
