# helm upgrade prometheus stable/prometheus-operator --install --namespace monitoring -f prometheus.yml

# https://github.com/helm/charts/blob/master/stable/prometheus-operator/values.yaml

fullnameOverride: prometheus

#### we have our own grafana instance
grafana:
  enabled: false

### following resources either controlled by GKE or absent
kubeDns:
  enabled: false
coreDns:
  enabled: false
kubeControllerManager:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false

### do not create default rules - will load them manually using jsonnet
defaultRules:
  create: false

### settings for the alert manager
alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi

  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ["alertname"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 24h


prometheus:
  prometheusSpec:
    ruleSelector:
      matchExpressions:
      - key: app
        operator: Exists
    serviceMonitorSelector:
      matchExpressions:
      - key: app
        operator: Exists
    resources:
      requests:
        cpu: 10m
        memory: 64Mi

prometheusOperator:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
