apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: backup
    type: $TYPE
    name: $NAME
  name: backup-$TYPE-$NAME
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app: backup
        type: $TYPE
        name: $NAME
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        spec:
          containers:
            - env:
                - name: CLOUDSDK_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: private_key
                      name: $SECRET_NAME
                - name: BUCKET_NAME
                  valueFrom:
                    secretKeyRef:
                      key: bucket_name
                      name: $SECRET_NAME
                - name: BACKUP_PATH
                  value: /backup/dump.tar.gz
                - name: BUCKET_PATH
                  value: "$TYPE/$NAME"
              image: makeomatic/cloud-backup:store
              imagePullPolicy: IfNotPresent
              name: store
              volumeMounts:
                - mountPath: /backup
                  name: backup-volume
          dnsPolicy: ClusterFirst
          initContainers:
            - env:
                - name: REDIS_HOST
                  value: $REDIS_HOST
                - name: REDIS_GROUP
                  value: $REDIS_GROUP
                - name: BACKUP_PATH
                  value: /backup/dump.tar.gz
              image: makeomatic/cloud-backup:$TYPE
              imagePullPolicy: IfNotPresent
              name: backup
              volumeMounts:
                - mountPath: /backup
                  name: backup-volume
          restartPolicy: Never
          volumes:
            - emptyDir: {}
              name: backup-volume
  schedule: "$SCHEDULE"
  successfulJobsHistoryLimit: 0
