replicaCount: 1

image:
  repository: vkfont/chatbot
  tag: latest

service:
  type: ClusterIP
  ports:
  - name: http
    port: 8080

env:
  - name: TOKEN
    value: 754996663:AAFm3miB8L1DODB_tGiI_xfSO5anwRO3Uq0
  - name: DEFAULT_CHANNEL
    value: "498146361"

health:
  checkLiveness: true
  checkReadiness: true
  liveness:
    httpGet:
      path: /health
      port: http
  readiness:
    httpGet:
      path: /health
      port: http

resources:
  requests:
    memory: 100Mi
    cpu: 10m
  limits:
    memory: 100Mi
    cpu: 100m

keel:
  policy: all
  trigger: poll
  pollSchedule: "@hourly"
  images:
    - repository: image.repository
      tag: image.tag
