cronjob:
  failedJobsHistoryLimit: 1
configMaps:
  config_yml: |-
    ---
    client:
      hosts:
        - elasticsearch-client
      port: 9200
  action_file_yml: |-
    ---
    actions:
      1:
        action: delete_indices
        description: "Clean up old microfleet logs"
        options:
          timeout_override: 300
          continue_if_exception: True
          ignore_empty_list: True
        filters:
        - filtertype: pattern
          kind: regex
          value: '^(microfleet).*$'
        - filtertype: age
          source: name
          direction: older
          timestring: '%Y.%m.%d'
          unit: days
          unit_count: 5
      # 2:
      #   action: delete_indices
      #   description: "Clean up jaeger logs older than 3 days"
      #   options:
      #     timeout_override: 300
      #     continue_if_exception: True
      #     ignore_empty_list: True
      #   filters:
      #   - filtertype: pattern
      #     kind: regex
      #     value: '^(jaeger).*$'
      #   - filtertype: age
      #     source: name
      #     direction: older
      #     timestring: '%Y-%m-%d'
      #     unit: days
      #     unit_count: 3
      # 3:
      #   action: delete_indices
      #   description: "Clean up APM old indexes"
      #   options:
      #     timeout_override: 300
      #     continue_if_exception: True
      #     ignore_empty_list: True
      #   filters:
      #   - filtertype: pattern
      #     kind: regex
      #     value: '^(apm-).*$'
      #   - filtertype: age
      #     source: name
      #     direction: older
      #     timestring: '%Y.%m.%d'
      #     unit: days
      #     unit_count: 3

keel:
  policy: major
  trigger: poll
  pollSchedule: "@hourly"
  images:
    - repository: image.repository
      tag: image.tag
