backend:
  type: es
  es:
    host: elasticsearch-client
    index: microfleet
    logstash_prefix: microfleet

trackOffsets: true

parsers:
  enabled: true
  json:
    - name: docker
      timeKeep: false
      timeKey: "@timestamp"
      timeFormat: "%Y-%m-%dT%H:%M:%S.%L"
      decodeFieldAs: escaped_utf8
      decodeField: log

# TODO: Error in line 12: Each key must have a value
# extraEntries:
#   ### do not log if pods aren't annotated with `fluentbit.io/enabled=*`
#   # kubectl -n sl-staging annotate pods fluentbit.io/enabled=true --all --overwrite
#   filter: |-

#     [FILTER]
#         Name                   modify
#         Match                  *
#         Copy                   kubernetes kubernetes_copy
#     [FILTER]
#         Name                   nest
#         Match                  *
#         Operation              lift
#         Nested_under           kubernetes_copy
#         Add_prefix             kubernetes_copy_
#     [FILTER]
#         Name                  nest
#         Match                 *
#         Operation             lift
#         Nested_under          kubernetes_copy_annotations
#         Prefix_with           kubernetes_copy_annotations_
#     [FILTER]
#         Name                  grep
#         Match                 *
#         Regex                 kubernetes_copy_annotations_fluentbit.io/enabled  *
#     [FILTER]
#         Name                  modify
#         Match                 *
#         Remove_wildcard       kubernetes_copy_

#     [FILTER]
#         Name modify
#         Match *
#         # if .msg exists - ok, otherwise try to fill it from the other fields
#         Rename message msg

#     [FILTER]
#         Name record_modifier
#         Match *
#         # avoid conflicts with dublicate fields
#         Remove_key time
#         Remove_key @timestamp
#         # log is already parsed in this moment, no need to store it twice
#         Remove_key log


### autoupdate image if new version is available
keel:
  policy: major
  trigger: poll
  pollSchedule: "@hourly"
  images:
    - repository: image.fluent_bit.repository
      tag: image.fluent_bit.tag


