loki:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

promtail:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  # https://github.com/grafana/loki/issues/393
  config:
    scrape_configs:
    - entry_parser: '{{ .Values.entryParser }}'
      job_name: kubernetes-pods-name
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: __service__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: drop
        regex: ^$
        source_labels:
        - __service__
      - action: replace
        replacement: $1
        separator: /
        source_labels:
        - __meta_kubernetes_namespace
        - __service__
        target_label: job
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container_name
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      # - replacement: /var/log/pods/$1/*.log
      #   separator: /
      #   source_labels:
      #   - __meta_kubernetes_pod_uid
      #   - __meta_kubernetes_pod_container_name
      #   target_label: __path__
      - replacement: /var/log/pods/*$1*/*/*.log
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: __path__
