config:
  datasource:
    host: sql-proxy
    user: postgres
    password:
    passwordSecret:
      name: sql-credentials
      key: pg_su_password

keel:
  policy: all
  trigger: poll
  pollSchedule: "@daily"
  images:
    - repository: image.repository
      tag: image.tag
