{
 "title": "Service monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(microfleet_request_duration_milliseconds_bucket, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Top success",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(delta(microfleet_request_duration_milliseconds_count{service=~\"$service\",route!~\".+health\",statusCode!~\"[45]..\"}[$__range]) > 0) by (route,statusCode))"
    }
   ]
  },
  {
   "title": "Top errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, sum(delta(microfleet_request_duration_milliseconds_count{service=~\"$service\",statusCode=~\"[45]..\"}[$__range]) > 0) by (route,statusCode))"
    }
   ]
  },
  {
   "title": "Top slowest",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "topk(5, \n\tsum(rate(microfleet_request_duration_milliseconds_sum{service=~\"$service\"}[$__range]) /\n\trate(microfleet_request_duration_milliseconds_count{service=~\"$service\"}[$__range])\n > 0) by (route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "Traffic / Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(microfleet_request_duration_milliseconds_count{service=~\"$service\",route!~\".+health\"}[$__range]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(rate(microfleet_request_duration_milliseconds_count{service=~\"$service\",route!~\".+health\",statusCode=~\"[4]..\"}[$__range]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(microfleet_request_duration_milliseconds_count{service=~\"$service\",route!~\".+health\",statusCode=~\"[5]..\"}[$__range]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(microfleet_request_duration_milliseconds_bucket{service=~\"$service\",route!~\".+health\"}[$__range])) by (le))",
     "legendFormat": "0.9 quantile"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(microfleet_request_duration_milliseconds_bucket{service=~\"$service\",route!~\".+health\"}[$__range])) by (le))",
     "legendFormat": "0.5 quantile"
    },
    {
     "expr": "sum(microfleet_request_duration_milliseconds_sum{service=~\"$service\",route!~\".+health\"})/sum(microfleet_request_duration_milliseconds_count{service=~\"$service\",route!~\".+health\"})",
     "legendFormat": "average"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "avg(sum(eagle_pod_container_resource_requests_cpu_cores{exported_pod=~\"^$service.*\"}) by (exported_pod))",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(sum(eagle_pod_container_resource_limits_cpu_cores{exported_pod=~\"^$service.*\"}) by (exported_pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_cpu_cores{exported_pod=~\"^$service.*\"}) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "avg(sum(eagle_pod_container_resource_requests_memory_bytes{exported_pod=~\"^$service.*\"}) by (exported_pod))",
     "legendFormat": "Requested"
    },
    {
     "expr": "avg(sum(eagle_pod_container_resource_limits_memory_bytes{exported_pod=~\"^$service.*\"}) by (exported_pod))",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(eagle_pod_container_resource_usage_memory_bytes{exported_pod=~\"^$service.*\"}) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Eventloop",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_lag_seconds{pod=~\"^$service.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active handlers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(nodejs_active_handles_total{pod=~\"^$service.*\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}