{{ readFile "../repositories.yaml" }}
---
{{ readFile "../defaults.yaml" }}
---
releases:
- name: openvpn
  namespace: default
  chart: stable/openvpn
  version: 3.x
  values:
  - values/openvpn.yml

- name: nginx-ingress
  namespace: default
  chart: stable/nginx-ingress
  version: 1.x
  values:
  - values/nginx-ingress.yml

- name: cert-manager
  namespace: default
  chart: stable/cert-manager
  version: 0.x
  values:
  - values/cert-manager.yml
