controller:
  replicaCount: 1

  metrics:
    enabled: false

  defaultBackendService: "kube-system/default-http-backend"

  service:
    loadBalancerIP: "" # gcloud compute addresses list

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

defaultBackend:
  enabled: false

rbac:
  create: true


keel:
  policy: minor
  trigger: poll
  pollSchedule: "@hourly"
  images:
    - repository: controller.image.repository
      tag: controller.image.tag
